### ISSUE TITLE
Ragel?

### ISSUE THREAD

**Issue by suntong** [mewspring/dot#3]
Hi Robin, 

I can tell that you are a big fan of gocc. Would you share your opinion on BNF based parsing vs [Ragel](http://thingsaaronmade.com/blog/a-simple-intro-to-writing-a-lexer-with-ragel.html), from which the blogger claimed that, "_It seems that there is a fair variety of tools designed to make writing Lexers, Scanners and Tokenizers easier, but Ragel has a reputation for being simple and consistently producing the fastest final code_"

PS. you can find out [more about Ragel here](https://docs.google.com/document/d/16sRuA3p7HWB4pg_6FeFdBMiSlL9_4wcPqsoxkfLYwiw/edit?usp=sharing) if you want to.

**Comment by mewmew** [comment]
> I can tell that you are a big fan of gocc. Would you share your opinion on BNF based parsing vs Ragel,

Hi Sun Tong,

I definitely enjoy playing with Gocc, and have so far been using it to write grammars for [LLVM IR](https://github.com/llir/spec/blob/master/gocc/ll.bnf), [µC](https://github.com/mewmew/uc/blob/master/gocc/uc.bnf) and now [DOT](https://github.com/graphism/dot/blob/master/internal/dot.bnf).

I did take a look at Ragel for one of my previous projects, but seeing as it is only used for generating lexers, I searched for other tools and came across Gocc. (There is also a port of [yacc](https://golang.org/cmd/yacc/) by the core Go team for generating parsers, which may be worth looking into)

The discussion at https://groups.google.com/forum/?_escaped_fragment_=topic/golang-nuts/h5eR60AXrB0#!topic/golang-nuts/h5eR60AXrB0 provides some interesting insights. Providing an extract from Ian Lance Taylor below.

> In practice parser generates are more useful than lexer generators.  A
> hand-written lexer is usually fairly easy to write and generally
> outperforms a generated lexer, at least with the lexer generators that
> I've seen.

I share this belief, that writing lexers is rather easy to do by hand (and even fun after having been introduced to Rob Pike's [Lexical Scanning in Go](https://www.youtube.com/watch?v=HxaD_trXwRE) talk). Parsers on the other hand contain a vast number of states, and one would have to be very careful not to introduce bugs, miss any state transitions or introduce any ambiguity. While DOT is a simple enough language, thus making it feasible to develop hand-written parsers, these tools really do make life so much easier. For instance, while writing the grammar for LLVM IR, Gocc managed to [identify an ambiguity](http://lists.llvm.org/pipermail/llvm-dev/2016-May/100110.html) related to unnamed global variables within the LLVM IR language, which have since been [resolved](http://reviews.llvm.org/rL269096#c4361726) by the LLVM project.

Gocc also produces a wealth of useful debug information, for instance, the LR1 sets, and makes it trivial to debug the lexer and parser (by passing the `-debug_lexer` and `-debug_parser` flags when generating the lexers and parsers). Attaching an example below.

Generate a parser with debugging enabled.

```
$ cd ${GOPATH}/src/github.com/graphism/dot/gocc
$ make debug_parser
```

Contents of `a.dot`:

``` dot
digraph {
    A -> B
}
```

Using [foo.go](https://play.golang.org/p/RHiRTs-yWS), a copy of which is hosted on play.golang.org, we can take a closer look at how the parser shifts and reduces the terminals and non-terminals to parse the input and finally end up in an accepting state.

```
$ go run foo.go a.dot
S0 digraph(7,digraph) reduce:4(OptStrict : empty    << false, nil >>)
S3 digraph(7,digraph) shift:8
S8 {(2,{) reduce:7(DirectedGraph : digraph  << true, nil >>)
S6 {(2,{) reduce:53(OptID : empty   << "", nil >>)
S9 {(2,{) shift:12
S12 id(19,A) shift:30
S30 ->(10,->) reduce:52(ID : id << astx.NewID(X[0]) >>)
S27 ->(10,->) reduce:50(OptPort : empty << nil, nil >>)
S44 ->(10,->) reduce:47(NodeID : ID OptPort << astx.NewNodeID(X[0], X[1]) >>)
S22 ->(10,->) reduce:45(Vertex : NodeID <<  >>)
S23 ->(10,->) shift:41
S41 id(19,B) reduce:23(DirectedEdge : "->"  << true, nil >>)
S39 id(19,B) shift:62
S62 }(3,}) reduce:52(ID : id    << astx.NewID(X[0]) >>)
S60 }(3,}) reduce:50(OptPort : empty    << nil, nil >>)
S44 }(3,}) reduce:47(NodeID : ID OptPort    << astx.NewNodeID(X[0], X[1]) >>)
S58 }(3,}) reduce:45(Vertex : NodeID    <<  >>)
S59 }(3,}) reduce:24(OptEdge : empty    << nil, nil >>)
S75 }(3,}) reduce:21(Edge : DirectedEdge Vertex OptEdge << astx.NewEdge(X[0], X[1], X[2]) >>)
S38 }(3,}) reduce:32(OptAttrList : empty    << nil, nil >>)
S56 }(3,}) reduce:20(EdgeStmt : Vertex Edge OptAttrList << astx.NewEdgeStmt(X[0], X[1], X[2]) >>)
S18 }(3,}) reduce:13(Stmt : EdgeStmt    <<  >>)
S16 }(3,}) reduce:17(OptSemi : empty    <<  >>)
S33 }(3,}) reduce:8(StmtList : Stmt OptSemi << astx.NewStmtList(X[0]) >>)
S15 }(3,}) reduce:11(OptStmtList : StmtList <<  >>)
S13 }(3,}) shift:31
S31 $(1,) reduce:3(Graph : OptStrict DirectedGraph OptID "{" OptStmtList "}"    << astx.NewGraph(X[0], X[1], X[2], X[4]) >>)
S2 $(1,) reduce:1(File : Graph  << astx.NewFile(X[0]) >>)
S1 $(1,) accept(0)
```

Extract of contents from `LR1_sets.txt` created by Gocc when verbosity is enabled (the `-v` flag):

```
S0{
    S' : •File «$»
    File : •Graph «$»
    File : •File Graph «$»
    Graph : •OptStrict DirectedGraph OptID { OptStmtList } «$»
    File : •Graph «digraph»
    File : •Graph «graphx»
    File : •Graph «strict»
    File : •File Graph «digraph»
    File : •File Graph «graphx»
    File : •File Graph «strict»
    OptStrict : empty• «digraph»
    OptStrict : empty• «graphx»
    OptStrict : •strict «digraph»
    OptStrict : •strict «graphx»
    Graph : •OptStrict DirectedGraph OptID { OptStmtList } «digraph»
    Graph : •OptStrict DirectedGraph OptID { OptStmtList } «graphx»
    Graph : •OptStrict DirectedGraph OptID { OptStmtList } «strict»
}
Transitions:
    File -> 1
    Graph -> 2
    OptStrict -> 3
    strict -> 4


S1{
    S' : File• «$»
    File : File •Graph «$»
    File : File •Graph «digraph»
    File : File •Graph «graphx»
    File : File •Graph «strict»
    Graph : •OptStrict DirectedGraph OptID { OptStmtList } «$»
    Graph : •OptStrict DirectedGraph OptID { OptStmtList } «digraph»
    Graph : •OptStrict DirectedGraph OptID { OptStmtList } «graphx»
    Graph : •OptStrict DirectedGraph OptID { OptStmtList } «strict»
    OptStrict : empty• «digraph»
    OptStrict : empty• «graphx»
    OptStrict : •strict «digraph»
    OptStrict : •strict «graphx»
}
Transitions:
    OptStrict -> 3
    strict -> 4
    Graph -> 5

...
```

It also produces files for inspecting the first sets of each non-terminal, and information about the regular expression used by the lexer to identify the lexemes.

All in all, it is a very lovely tool to use! Thanks goes to both @awalterschulze and @goccmack for developing it in the first place, and releasing it to the open source community!

Cheers /u

**Comment by mewmew** [comment]
Closing this issue for now, as we have yet to identify any issues with the lexer generated by Gocc. If in the future, we notice a performance issue and through profiling discover that it is related to lexing, then we may definitely wish to re-open this issue and take a deeper look at hooking in a Regel generated lexer, to see if it would improve the performance.

Feel free to reopen, if there is something else you may wish to discuss related to Ragel. Otherwise, open a new dedicated issue for other generators (such as yacc).

**Comment by suntong** [comment]
Sure. Thank for the detailed explanations.
