### ISSUE TITLE
 Gocc dependency

### ISSUE THREAD

**Issue by suntong** [mewspring/dot#4]
My understanding is that the Gocc compiler kit is used to generate lexers and parsers from the BNF grammar of the DOT file format.

If so, would you think it is a good idea not to enforce this Gocc dependency to dot users by separating the building process into a different package, while dot only makes use of the generated code? It's like there are two level of dependencies as well for Debian packages -- the dependencies to build it and the dependencies to run it, which has far less dependencies than that of building it, most of the time.

**Comment by mewmew** [comment]
> If so, would you think it is a good idea not to enforce this Gocc dependency to dot users

Definitely. The `dot` package will be made go get'able before it reaches version 1.0, that's for sure. Once the API has become stable enough, and the grammar weathered and battle tests, the source code of the generated lexers and parsers will be checked into the repository (this is also how gographviz does it).

Thanks for opening an issue about it. Marking it for the 1.0 release.

**Comment by suntong** [comment]
Bravo! Congrats for reaching version 1.0!

So this means that the dot package is go get'able now?

**Comment by mewmew** [comment]
> Bravo! Congrats for reaching version 1.0!

Haha, thanks. However, we have not reached 1.0 yet :) This issue was the only issue attached to the 1.0 milestone, which is why it looks completed. [Version 0.1](https://github.com/graphism/dot/milestone/1) is still to be released. Version 1.0 will happen once we have settled on a stable API.

There are still a few things I am trying to flesh out regarding the API for converting back and forth from [*ast.Graph](https://godoc.org/github.com/graphism/dot/ast#Graph) to [gonum.Graph](https://godoc.org/github.com/gonum/graph#Graph). Right now, it works for directed graphs (with support for undirected graphs yet to be added). What I would like to see is some way to transfer some information from the DOT graph, such as node names, and perhaps common attributes. Still haven't figured out just how this may work yet. So, feel free to give any input or suggest ideas.

I reckon these things will become more stable as we have a few use cases in mind, and try to settle on a minimal API which supports their requirements.

> So this means that the dot package is go get'able now?

It is indeed.

**Comment by mewmew** [comment]
Refer to #6 which tracks the API stability for the 1.0 release.

**Comment by suntong** [comment]
OK. looking forward to the stabled API (and some sample code, like [my previous dot testing program](https://github.com/suntong/lang/blob/master/lang/Go/src/graph/DotDemo1.go) which was duplicated from your samples).  The [dotu.go](https://github.com/suntong/lang/blob/master/lang/Go/src/graph/dotu.go) tested fine now.
